import {
  AssessmentQuestion,
  AssessmentSubmission,
  ConsultationLead,
  SituationSummary,
  GuidanceResource,
  TestimonialItem,
  FaqItem,
} from "@/types";

export const initialQuestions: AssessmentQuestion[] = [
  {
    id: 1,
    question: {
      de: "FÃ¼r wen sorgen Sie?",
      en: "Who are you caring for?",
      fr: "Pour qui prenez-vous soin?",
      it: "Di chi ti prendi cura?",
    },
    subtitle: {
      de: "WÃ¤hlen Sie die passendste Option",
      en: "Choose the closest match",
      fr: "Choisissez l'option la plus proche",
      it: "Scegli la corrispondenza piÃ¹ vicina",
    },
    category: "relation",
    options: [
      "Ein Elternteil oder Schwiegereltern",
      "Ein Partner oder Ehepartner",
      "Ein Kind",
      "Anderes Familienmitglied / Freund",
    ],
    isActive: true,
  },
  {
    id: 2,
    question: {
      de: "Wie ist die aktuelle Wohnsituation?",
      en: "What is their current living arrangement?",
      fr: "Quel est leur mode de vie actuel?",
      it: "Qual Ã¨ la loro attuale sistemazione abitativa?",
    },
    subtitle: {
      de: "WÃ¤hlen Sie die primÃ¤re Wohnform",
      en: "Select the primary living situation",
      fr: "SÃ©lectionnez le mode de vie principal",
      it: "Seleziona la situazione abitativa primaria",
    },
    category: "living",
    options: [
      "EigenstÃ¤ndig zu Hause",
      "Im selben Haushalt mit mir",
      "In einer Pflegeeinrichtung / Betreutes Wohnen",
      "Andere Wohnsituation",
    ],
    isActive: true,
  },
  {
    id: 3,
    question: {
      de: "Welche tÃ¤gliche UnterstÃ¼tzung ist erforderlich?",
      en: "What level of daily assistance is currently needed?",
      fr: "Quel niveau d'assistance quotidienne est nÃ©cessaire?",
      it: "Quale livello di assistenza quotidiana Ã¨ attualmente necessario?",
    },
    subtitle: {
      de: "WÃ¤hlen Sie das Niveau der tÃ¤glichen Hilfe",
      en: "Select the most accurate level of daily support",
      fr: "SÃ©lectionnez le niveau le plus prÃ©cis",
      it: "Seleziona il livello di supporto piÃ¹ accurato",
    },
    category: "assistance",
    options: [
      "Leichte Hilfe (Einkauf, BehÃ¶rden, Haushalt)",
      "Mittlere Hilfe (Mahlzeiten, Medikamente, MobilitÃ¤t)",
      "Intensive 24/7 Betreuung (KÃ¶rperpflege, Aufsicht)",
      "Unsicher / Bedarf wird aktuell abgeklÃ¤rt",
    ],
    isActive: true,
  },
  {
    id: 4,
    question: {
      de: "Liegt bereits ein offizieller Pflegegrad vor?",
      en: "Has a formal Pflegegrad (care degree) been assigned?",
      fr: "Un degrÃ© de soins formel a-t-il Ã©tÃ© attribuÃ©?",
      it: "Ãˆ stato assegnato un livello di cura formale?",
    },
    subtitle: {
      de: "Einstufung der PflegebedÃ¼rftigkeit in der Schweiz",
      en: "Swiss / German care classification level",
      fr: "Niveau de classification suisse",
      it: "Livello di classificazione svizzero",
    },
    category: "pflegegrad",
    options: [
      "Ja (Pflegegrad 1 - 2)",
      "Ja (Pflegegrad 3 - 5)",
      "Antrag lÃ¤uft aktuell",
      "Nein / Noch nicht beantragt",
    ],
    isActive: true,
  },
  {
    id: 5,
    question: {
      de: "Was ist aktuell Ihre grÃ¶sste Herausforderung?",
      en: "What is your biggest current caregiving challenge?",
      fr: "Quel est votre plus grand dÃ©fi actuel?",
      it: "Qual Ã¨ la tua piÃ¹ grande sfida attuale?",
    },
    subtitle: {
      de: "Wo spÃ¼ren Sie den grÃ¶ssten UnterstÃ¼tzungsbedarf?",
      en: "Where do you feel the most pressure today?",
      fr: "OÃ¹ ressentez-vous le plus de pression?",
      it: "Dove senti la maggior pressione oggi?",
    },
    category: "challenges",
    options: [
      "BÃ¼rokratie, Recht & VersicherungsansprÃ¼che",
      "Emotionale ErschÃ¶pfung & Ãœberlastung der AngehÃ¶rigen",
      "Vereinbarkeit von Beruf, Familie & Pflege",
      "Finanzielle Belastung & KostenÃ¼bernahme",
    ],
    isActive: true,
  },
  {
    id: 6,
    question: {
      de: "Erhalten Sie Hilfe von AngehÃ¶rigen oder Geschwistern?",
      en: "Do you have support from other family members or siblings?",
      fr: "Avez-vous le soutien d'autres membres de la famille?",
      it: "Hai il supporto di altri membri della famiglia?",
    },
    subtitle: {
      de: "Betreuungsnetzwerk und Aufgabenteilung in der Familie",
      en: "Care network and shared responsibilities",
      fr: "RÃ©seau de soins et responsabilitÃ©s partagÃ©es",
      it: "Rete di assistenza e responsabilitÃ  condivise",
    },
    category: "network",
    options: [
      "Ja, Aufgaben sind gut im Umfeld verteilt",
      "Etwas Hilfe, aber Hauptverantwortung liegt bei mir",
      "Nein, ich trage die Betreuung vollstÃ¤ndig allein",
      "Es bestehen Meinungsverschiedenheiten in der Familie",
    ],
    isActive: true,
  },
  {
    id: 7,
    question: {
      de: "Ist bereits ein ambulanter Pflegedienst (Spitex) involviert?",
      en: "Are professional outpatient care services (Spitex) involved?",
      fr: "Des services de soins ambulatoires (Spitex) sont-ils impliquÃ©s?",
      it: "Sono coinvolti servizi di assistenza ambulatoriale (Spitex)?",
    },
    subtitle: {
      de: "Professionelle Pflege und UnterstÃ¼tzung zu Hause",
      en: "External nursing and in-home care support",
      fr: "Soutien infirmier Ã  domicile",
      it: "Assistenza infermieristica e domiciliare",
    },
    category: "spitex",
    options: [
      "Ja, tÃ¤gliche Spitex-EinsÃ¤tze",
      "Ja, mehrmals pro Woche",
      "Spitex-Einbezug wird aktuell geprÃ¼ft",
      "Aktuell keine professionellen Pflegedienste",
    ],
    isActive: true,
  },
  {
    id: 8,
    question: {
      de: "Liegen wichtige rechtliche Vorsorgedokumente vor?",
      en: "Are essential legal documents in place?",
      fr: "Les documents juridiques essentiels sont-ils en place?",
      it: "I documenti legali essenziali sono pronti?",
    },
    subtitle: {
      de: "PatientenverfÃ¼gung und Vorsorgeauftrag gemÃ¤ss Schweizer Recht",
      en: "Powers of attorney and healthcare directives",
      fr: "Mandat pour cause d'inaptitude et directives anticipÃ©es",
      it: "Procure e direttive anticipate",
    },
    category: "legal",
    options: [
      "Ja, Vorsorgeauftrag & PatientenverfÃ¼gung vollstÃ¤ndig geregelt",
      "Teilweise vorhanden / in Bearbeitung",
      "Noch nicht erstellt",
      "Unsicher, welche Dokumente rechtlich erforderlich sind",
    ],
    isActive: true,
  },
  {
    id: 9,
    question: {
      de: "Wie steht es um Ihr persÃ¶nliches Wohlbefinden?",
      en: "How is your personal emotional well-being?",
      fr: "Comment est votre bien-Ãªtre Ã©motionnel?",
      it: "Come sta il tuo benessere emotivo personale?",
    },
    subtitle: {
      de: "Ihre eigene Gesundheit und Belastung als pflegende(r) AngehÃ¶rige(r)",
      en: "Your own health and stress levels as a caregiver",
      fr: "Votre propre santÃ© et niveau de stress",
      it: "La tua salute e il livello di stress",
    },
    category: "wellbeing",
    options: [
      "Gut bewÃ¤ltigbar mit stabiler Balance",
      "HÃ¤ufig gestresst, aber noch handhabbar",
      "Stark Ã¼berlastet und nahe an der ErschÃ¶pfung",
      "Dringender Entlastungsbedarf zur Erholung",
    ],
    isActive: true,
  },
  {
    id: 10,
    question: {
      de: "In welchem Schweizer Kanton oder welcher Region leben Sie?",
      en: "What is your Canton or geographic region in Switzerland?",
      fr: "Quel est votre canton en Suisse?",
      it: "Qual Ã¨ il tuo Cantone in Svizzera?",
    },
    subtitle: {
      de: "Regionale Beratungsangebote sind kantonal geregelt",
      en: "Guidance is tailored to local Cantonal regulations",
      fr: "Conseils adaptÃ©s aux rÃ¨gles cantonales",
      it: "Guida su misura per le normative cantonali",
    },
    category: "canton",
    options: [
      "ZÃ¼rich / Nordostschweiz",
      "Bern / Espace Mittelland",
      "Romandie (Genf, Waadt, Wallis, Neuenburg)",
      "Zentralschweiz / Tessin / Ãœbrige Kantone",
    ],
    isActive: true,
  },
  {
    id: 11,
    question: {
      de: "Besteht Interesse an vorÃ¼bergehenden Entlastungsangeboten?",
      en: "Are you interested in respite care (Entlastungsangebote)?",
      fr: "ÃŠtes-vous intÃ©ressÃ© par des offres de rÃ©pit?",
      it: "Sei interessato alle offerte di sollievo?",
    },
    subtitle: {
      de: "TagesstÃ¤tten, Kurzzeitpflege oder Entlastungsdienst",
      en: "Temporary day care, holiday relief, or night care",
      fr: "Accueil de jour, rÃ©pit temporaire",
      it: "Centri diurni, sollievo temporaneo",
    },
    category: "respite",
    options: [
      "Ja, dringend auf der Suche nach Entlastung",
      "Ja, als Vorsorge fÃ¼r kÃ¼nftige Bedarfe",
      "MÃ¶chte mich Ã¼ber MÃ¶glichkeiten informieren",
      "Aktuell kein Entlastungsbedarf",
    ],
    isActive: true,
  },
  {
    id: 12,
    question: {
      de: "Was ist Ihr Hauptziel mit dem Pflege-Kompass?",
      en: "What is your primary goal from this Care Compass?",
      fr: "Quel est votre objectif principal?",
      it: "Qual Ã¨ il tuo obiettivo principale?",
    },
    subtitle: {
      de: "Wie wir Sie am besten gezielt unterstÃ¼tzen kÃ¶nnen",
      en: "How Polaris can best guide your next steps",
      fr: "Comment Polaris peut vous guider",
      it: "Come possiamo guidarti al meglio",
    },
    category: "goals",
    options: [
      "Strukturierter Schritt-fÃ¼r-Schritt-Plan fÃ¼r unsere Familie",
      "Finanzielle Klarheit Ã¼ber ErgÃ¤nzungsleistungen (EL/AHV)",
      "Notfallplanung & EntlastungsmÃ¶glichkeiten",
      "Vermittlung akkreditierter regionaler Beratungsstellen",
    ],
    isActive: true,
  },
];

export const initialSubmissions: AssessmentSubmission[] = [
  {
    id: "CC-9014",
    caregiver: "Elena Fischer",
    relation: "Mutter (84 Jahre)",
    living: "EigenstÃ¤ndig zu Hause",
    careDegree: "Pflegegrad 3 - 5",
    urgency: "High",
    canton: "ZÃ¼rich (ZH)",
    submittedAt: "Vor 10 Min.",
    score: 84,
    status: "Pending Action",
    answers: {
      1: "Ein Elternteil oder Schwiegereltern",
      2: "EigenstÃ¤ndig zu Hause",
      3: "Mittlere Hilfe (Mahlzeiten, Medikamente, MobilitÃ¤t)",
      4: "Ja (Pflegegrad 3 - 5)",
      5: "Emotionale ErschÃ¶pfung & Ãœberlastung der AngehÃ¶rigen",
      6: "Nein, ich trage die Betreuung vollstÃ¤ndig allein",
      7: "Spitex-Einbezug wird aktuell geprÃ¼ft",
      8: "Teilweise vorhanden / in Bearbeitung",
      9: "Dringender Entlastungsbedarf zur Erholung",
      10: "ZÃ¼rich / Nordostschweiz",
      11: "Ja, dringend auf der Suche nach Entlastung",
      12: "Notfallplanung & EntlastungsmÃ¶glichkeiten",
    },
    advisorNotes: "Alleinpflegende Tochter mit starker Ãœberlastung. Dringende Spitex-ErhÃ¶hung und Entlastungsdienst ZÃ¼rich empfohlen.",
  },
  {
    id: "CC-9013",
    caregiver: "Marc Baumgartner",
    relation: "Ehepartnerin",
    living: "Im selben Haushalt mit mir",
    careDegree: "Antrag lÃ¤uft",
    urgency: "Medium",
    canton: "Bern (BE)",
    submittedAt: "Vor 35 Min.",
    score: 62,
    status: "Reviewed",
    answers: {
      1: "Ein Partner oder Ehepartner",
      2: "Im selben Haushalt mit mir",
      3: "Mittlere Hilfe (Mahlzeiten, Medikamente, MobilitÃ¤t)",
      4: "Antrag lÃ¤uft aktuell",
      5: "BÃ¼rokratie, Recht & VersicherungsansprÃ¼che",
      6: "Etwas Hilfe, aber Hauptverantwortung liegt bei mir",
      7: "Ja, mehrmals pro Woche",
      8: "Ja, Vorsorgeauftrag & PatientenverfÃ¼gung vollstÃ¤ndig geregelt",
      9: "HÃ¤ufig gestresst, aber noch handhabbar",
      10: "Bern / Espace Mittelland",
      11: "Ja, als Vorsorge fÃ¼r kÃ¼nftige Bedarfe",
      12: "Finanzielle Klarheit Ã¼ber ErgÃ¤nzungsleistungen (EL/AHV)",
    },
    advisorNotes: "UnterstÃ¼tzung bei kantonalen ErgÃ¤nzungsleistungen Bern und HilflosenentschÃ¤digung zugestellt.",
  },
  {
    id: "CC-9012",
    caregiver: "Sophie Dubois",
    relation: "Vater",
    living: "Betreutes Wohnen",
    careDegree: "Pflegegrad 1 - 2",
    urgency: "Normal",
    canton: "Waadt (VD)",
    submittedAt: "Vor 2 Std.",
    score: 38,
    status: "Reviewed",
    answers: {
      1: "Ein Elternteil oder Schwiegereltern",
      2: "In einer Pflegeeinrichtung / Betreutes Wohnen",
      3: "Leichte Hilfe (Einkauf, BehÃ¶rden, Haushalt)",
      4: "Ja (Pflegegrad 1 - 2)",
      5: "Vereinbarkeit von Beruf, Familie & Pflege",
      6: "Ja, Aufgaben sind gut im Umfeld verteilt",
      7: "Ja, tÃ¤gliche Spitex-EinsÃ¤tze",
      8: "Ja, Vorsorgeauftrag & PatientenverfÃ¼gung vollstÃ¤ndig geregelt",
      9: "Gut bewÃ¤ltigbar mit stabiler Balance",
      10: "Romandie (Genf, Waadt, Wallis, Neuenburg)",
      11: "Aktuell kein Entlastungsbedarf",
      12: "Strukturierter Schritt-fÃ¼r-Schritt-Plan fÃ¼r unsere Familie",
    },
  },
  {
    id: "CC-9011",
    caregiver: "Marco Bernasconi",
    relation: "FamilienangehÃ¶riger",
    living: "Im selben Haushalt mit mir",
    careDegree: "Pflegegrad 3 - 5",
    urgency: "High",
    canton: "Tessin (TI)",
    submittedAt: "Vor 4 Std.",
    score: 91,
    status: "Pending Action",
    answers: {
      1: "Ein Elternteil oder Schwiegereltern",
      2: "Im selben Haushalt mit mir",
      3: "Intensive 24/7 Betreuung (KÃ¶rperpflege, Aufsicht)",
      4: "Ja (Pflegegrad 3 - 5)",
      5: "Emotionale ErschÃ¶pfung & Ãœberlastung der AngehÃ¶rigen",
      6: "Nein, ich trage die Betreuung vollstÃ¤ndig allein",
      7: "Ja, tÃ¤gliche Spitex-EinsÃ¤tze",
      8: "Teilweise vorhanden / in Bearbeitung",
      9: "Stark Ã¼berlastet und nahe an der ErschÃ¶pfung",
      10: "Zentralschweiz / Tessin / Ãœbrige Kantone",
      11: "Ja, dringend auf der Suche nach Entlastung",
      12: "Notfallplanung & EntlastungsmÃ¶glichkeiten",
    },
  },
  {
    id: "CC-9010",
    caregiver: "Lukas Keller",
    relation: "AngehÃ¶riger",
    living: "EigenstÃ¤ndig zu Hause",
    careDegree: "Noch nicht beantragt",
    urgency: "Medium",
    canton: "Basel-Stadt (BS)",
    submittedAt: "Vor 6 Std.",
    score: 55,
    status: "Reviewed",
    answers: {
      1: "Anderes Familienmitglied / Freund",
      2: "EigenstÃ¤ndig zu Hause",
      3: "Leichte Hilfe (Einkauf, BehÃ¶rden, Haushalt)",
      4: "Nein / Noch nicht beantragt",
      5: "Finanzielle Belastung & KostenÃ¼bernahme",
      6: "Etwas Hilfe, aber Hauptverantwortung liegt bei mir",
      7: "Aktuell keine professionellen Pflegedienste",
      8: "Noch nicht erstellt",
      9: "HÃ¤ufig gestresst, aber noch handhabbar",
      10: "ZÃ¼rich / Nordostschweiz",
      11: "MÃ¶chte mich Ã¼ber MÃ¶glichkeiten informieren",
      12: "Vermittlung akkreditierter regionaler Beratungsstellen",
    },
  },
];

export const initialLeads: ConsultationLead[] = [
  {
    id: "LEAD-301",
    name: "Elena Fischer",
    phone: "+41 44 289 12 04",
    email: "elena.fischer@bluewin.ch",
    canton: "ZÃ¼rich (ZH)",
    urgency: "High",
    status: "new",
    preferredTime: "Vormittag (09:00 - 11:00)",
    message: "Ich betreue meine 84-jÃ¤hrige Mutter mit hohem Pflegeaufwand. Ich fÃ¼hle mich stark Ã¼berlastet und benÃ¶tige dringend Beratung zu Entlastungsdiensten im Kanton ZÃ¼rich.",
    assessmentId: "CC-9014",
    createdAt: "Heute, 09:15",
    notes: ["Erstanfrage Ã¼ber Pflege-Kompass erhalten.", "Hohe Dringlichkeit fÃ¼r Beraterkontakt markiert."],
  },
  {
    id: "LEAD-302",
    name: "Dr. Andreas Weber",
    phone: "+41 31 310 44 20",
    email: "andreas.weber@sunrise.ch",
    canton: "Bern (BE)",
    urgency: "Medium",
    status: "contacted",
    preferredTime: "Nachmittag (14:00 - 16:00)",
    message: "Suche unabhÃ¤ngige Beratung bezÃ¼glich Spitex-KostenÃ¼bernahme und ErgÃ¤nzungsleistungen im Kanton Bern.",
    assessmentId: "CC-9013",
    assignedAdvisor: "Dr. Hans Meier (ZÃ¼rich Berater)",
    createdAt: "Gestern, 14:30",
    notes: ["Erstkontakt per E-Mail mit Berner Spitex-Unterlagen versendet.", "Folgetermin fÃ¼r Donnerstag vereinbart."],
  },
  {
    id: "LEAD-303",
    name: "Isabelle Favre",
    phone: "+41 22 730 88 11",
    email: "isabelle.favre@gmail.com",
    canton: "Genf (GE)",
    urgency: "High",
    status: "scheduled",
    preferredTime: "Abend (17:00 - 19:00)",
    message: "Dringende Frage zu Vorsorgeauftrag, KESB-Richtlinien und PatientenverfÃ¼gung.",
    assessmentId: "CC-9011",
    assignedAdvisor: "Claire Blanc (Romandie Spezialistin)",
    createdAt: "20. Aug, 11:00",
    notes: ["BeratungsgesprÃ¤ch fÃ¼r 24. Aug, 17:30 per Video-Call gebucht."],
  },
  {
    id: "LEAD-304",
    name: "Hansruedi Steiner",
    phone: "+41 41 220 55 90",
    email: "h.steiner@quickline.ch",
    canton: "Luzern (LU)",
    urgency: "Standard",
    status: "resolved",
    preferredTime: "Jederzeit",
    message: "Pflege-Kompass fÃ¼r meinen Vater abgeschlossen. Vielen Dank fÃ¼r den strukturierten Leitfaden!",
    assignedAdvisor: "Dr. Hans Meier (ZÃ¼rich Berater)",
    createdAt: "18. Aug, 16:20",
    notes: ["Beratung erfolgreich abgeschlossen. Massgeschneiderter Leitfaden zugestellt."],
  },
];

export const initialSummaries: SituationSummary[] = [
  {
    id: "SUM-01",
    title: {
      de: "Stabile Betreuungssituation mit Entwicklungsbedarf",
      en: "Stable Care Situation with Emerging Support Needs",
      fr: "Situation de soins stable avec besoins d'accompagnement émergents",
      it: "Situazione assistenziale stabile con bisogni di supporto emergenti",
    },
    description: {
      de: "Ihre Angaben zeigen eine grundsätzlich funktionierende, aber zunehmend fordernde Pflegesituation zu Hause. Während die medizinische Grundversorgung gewährleistet ist, wächst der Bedarf an emotionaler Entlastung und gezielten Hilfsmitteln. Durch optimierte Einsatzplanung und Entlastungsdienste kann die Belastung der Angehörigen spürbar gesenkt werden.",
      en: "Your responses indicate a generally functioning but increasingly demanding care situation at home. While basic medical care is ensured, the need for emotional relief and specialized assistive devices is growing. Optimized scheduling and relief services can noticeably reduce caregiver strain.",
      fr: "Vos réponses indiquent une situation de soins à domicile globalement fonctionnelle mais de plus en plus exigeante. Alors que les soins médicaux de base sont assurés, le besoin de soutien émotionnel et d'aides techniques augmente.",
      it: "Le vostre risposte indicano una situazione assistenziale a domicilio generalmente funzionante ma sempre più impegnativa. Mentre l'assistenza medica di base è garantita, cresce il bisogno di sollievo emotivo e ausili mirati.",
    },
    targetCategory: {
      de: "Mittlerer Pflegebedarf, häusliche Pflege",
      en: "Moderate Care Need, Home Care",
      fr: "Besoin de soins modéré, soins à domicile",
      it: "Bisogno di cura moderato, assistenza domiciliare",
    },
    isActive: true,
  },
  {
    id: "SUM-02",
    title: {
      de: "Hohe Dringlichkeit & Entlastungsbedarf für Angehörige",
      en: "High Urgency & Immediate Relief for Family Caregivers",
      fr: "Urgence élevée & besoin de répit pour les proches aidants",
      it: "Alta urgenza & bisogno di sollievo per i familiari curanti",
    },
    description: {
      de: "Ihre Antworten deuten auf eine akute Erschöpfung und hohe 24/7-Betreuungsintensität hin. Prioritär sollte ein regionaler Entlastungsdienst (SRK / Pro Senectute) und eine Erweiterung der Spitex-Einsätze aktiviert werden, um einen gesundheitlichen Zusammenbruch der pflegenden Angehörigen zu verhindern.",
      en: "Your answers point to acute exhaustion and high 24/7 care intensity. Priority should be given to activating regional respite services (Red Cross / Pro Senectute) and expanding Spitex home nursing to prevent caregiver burnout.",
      fr: "Vos réponses indiquent un épuisement aigu et une forte intensité de soins 24h/24. La priorité devrait être d'activer un service de répit régional (Croix-Rouge / Pro Senectute) et d'élargir les interventions Spitex.",
      it: "Le risposte indicano un esaurimento acuto e un'elevata intensità di assistenza 24/7. La priorità dovrebbe essere l'attivazione di un servizio di sollievo regionale (Croce Rossa / Pro Senectute) e l'ampliamento degli interventi Spitex.",
    },
    targetCategory: {
      de: "Hohe Dringlichkeit, 24/7 Betreuung",
      en: "High Urgency, 24/7 Care",
      fr: "Haute urgence, soins 24h/24",
      it: "Alta urgenza, assistenza 24/7",
    },
    isActive: true,
  },
  {
    id: "SUM-03",
    title: {
      de: "Frühzeitige Orientierung & Vorsorgeplanung",
      en: "Early Orientation & Advance Healthcare Planning",
      fr: "Orientation précoce & planification anticipée",
      it: "Orientamento precoce & pianificazione previdenziale",
    },
    description: {
      de: "Sie befinden sich in der Orientierungsphase. Nutzen Sie diese Zeit, um rechtliche Dokumente (Vorsorgeauftrag, Patientenverfügung) aufzusetzen und Kontakt mit kantonalen Anlaufstellen zu knüpfen, bevor akute Betreuungsengpässe entstehen.",
      en: "You are in the initial orientation phase. Use this time to set up legal documents (advance health directives, power of attorney) and connect with cantonal advisory offices before acute care bottlenecks arise.",
      fr: "Vous êtes en phase d'orientation. Profitez de ce temps pour rédiger les documents juridiques (mandat pour cause d'inaptitude, directives anticipées) et contacter les centres cantonaux.",
      it: "Vi trovate nella fase di orientamento. Utilizzate questo tempo per redigere i documenti legali (mandato precauzionale, direttive del paziente) e stabilire contatti con i centri cantonali.",
    },
    targetCategory: {
      de: "Leichte Unterstützung, Frühphase",
      en: "Mild Support, Early Stage",
      fr: "Soutien léger, stade précoce",
      it: "Supporto lieve, fase iniziale",
    },
    isActive: true,
  },
];

export const initialResources: GuidanceResource[] = [
  {
    id: "RES-01",
    title: {
      de: "Physiotherapie & Mobilitätsberatung",
      en: "Physical Therapy & Mobility Consultation",
      fr: "Physiothérapie & conseil en mobilité",
      it: "Fisioterapia & consulenza sulla mobilità",
    },
    description: {
      de: "Akkreditierte spezialisierte Therapeuten für Sturzprophylaxe und Bewegungsförderung im häuslichen Umfeld.",
      en: "Accredited specialist therapists for fall prevention and mobility enhancement in the home environment.",
      fr: "Thérapeutes spécialisés accrédités pour la prévention des chutes et l'amélioration de la mobilité à domicile.",
      it: "Terapisti specializzati accreditati per la prevenzione delle cadute e la promozione del movimento a domicilio.",
    },
    category: "therapy",
    cantons: ["Zürich (ZH)", "Bern (BE)", "Waadt (VD)", "Ganze Schweiz"],
    linkUrl: "https://polaris-care.ch/resources/therapy",
    isActive: true,
  },
  {
    id: "RES-02",
    title: {
      de: "Lokaler Angehörigen-Treffpunkt (CareCircle)",
      en: "Local Family Caregiver Support Group (CareCircle)",
      fr: "Groupe de soutien local pour proches aidants (CareCircle)",
      it: "Gruppo di supporto locale per familiari curanti (CareCircle)",
    },
    description: {
      de: "Erfahrungsaustausch und gegenseitige Unterstützung mit anderen pflegenden Familien in Ihrer Region.",
      en: "Peer exchange and mutual support with other caregiving families in your region.",
      fr: "Échange d'expériences et soutien mutuel avec d'autres familles aidantes de votre région.",
      it: "Scambio di esperienze e sostegno reciproco con altre famiglie curanti della vostra regione.",
    },
    category: "community",
    cantons: ["Zürich (ZH)", "Bern (BE)", "Luzern (LU)", "Ganze Schweiz"],
    linkUrl: "https://polaris-care.ch/resources/carecircle",
    isActive: true,
  },
  {
    id: "RES-03",
    title: {
      de: "Hilfsmittel & Wohnraumanpassung",
      en: "Assistive Equipment & Home Modification Guide",
      fr: "Moyens auxiliaires & adaptation du logement",
      it: "Ausili & adattamento degli spazi abitativi",
    },
    description: {
      de: "Leitfaden für barrierefreie Badezimmer, Treppenlifte und adaptive Alltagshilfen mit kantonalen Zuschüssen.",
      en: "Guide for barrier-free bathrooms, stairlifts, and adaptive daily living aids with cantonal subsidies.",
      fr: "Guide pour salles de bain accessibles, monte-escaliers et aides quotidiennes avec subventions cantonales.",
      it: "Guida per bagni privi di barriere, montascale e ausili per la vita quotidiana con sussidi cantonali.",
    },
    category: "equipment",
    cantons: ["Ganze Schweiz"],
    linkUrl: "https://polaris-care.ch/resources/equipment",
    isActive: true,
  },
];

export const initialTestimonials: TestimonialItem[] = [
  {
    id: 1,
    name: "Sarah Renner",
    role: {
      de: "Pflegende Angehörige, Zürich",
      en: "Family Caregiver, Zurich",
      fr: "Proche aidante, Zurich",
      it: "Familiare curante, Zurigo",
    },
    canton: "Zürich (ZH)",
    quote: {
      de: "Der Pflege-Kompass war unkompliziert auszufüllen und die Empfehlungen genau auf unsere Situation im Kanton Zürich abgestimmt. Statt stundenlang im Internet nach Antworten zu suchen, hatten wir innerhalb von 5 Minuten Klarheit über unsere nächsten Schritte.",
      en: "The Care Compass assessment was straightforward to complete and the recommendations were perfectly tailored to our family situation in Canton Zurich. Instead of spending hours searching online, we had clarity on our next steps in just 5 minutes.",
      fr: "L'évaluation Care Compass était simple à remplir et les recommandations parfaitement adaptées à notre situation dans le canton de Zurich. En 5 minutes, nous avions des réponses claires sur nos prochaines étapes.",
      it: "Il questionario Care Compass è stato facile da compilare e le raccomandazioni erano perfettamente calibrate sulla nostra situazione nel Canton Zurigo. In 5 minuti abbiamo avuto piena chiarezza sui passi successivi.",
    },
    image: "/images/sarah.jpg",
    imageUrl: "/images/sarah.jpg",
    isVerified: true,
  },
  {
    id: 2,
    name: "Angel Dia",
    role: {
      de: "Ehepartnerin & Betreuerin, Bern",
      en: "Spouse & Caregiver, Bern",
      fr: "Conjointe & aidante, Berne",
      it: "Coniuge & curante, Berna",
    },
    canton: "Bern (BE)",
    quote: {
      de: "Pflege Orientierung hat uns geholfen, unsere Ansprüche bei den Ergänzungsleistungen (EL) zu verstehen und den passenden Spitex-Dienst in Bern zu finden. Die Erleichterung für unsere Familie war sofort spürbar.",
      en: "Pflege Orientierung helped us understand our rights regarding supplementary financial benefits (EL) and find the right accredited Spitex home care provider in Bern. The relief for our family was immediate.",
      fr: "Pflege Orientierung nous a aidés à comprendre nos droits aux prestations complémentaires (PC) et à trouver le bon service Spitex à Berne. Le soulagement pour notre famille a été immédiat.",
      it: "Pflege Orientierung ci ha aiutato a comprendere i nostri diritti alle prestazioni complementari (PC) e a trovare il servizio Spitex adatto a Berna. Il sollievo per la nostra famiglia è stato immediato.",
    },
    image: "/images/angel.jpg",
    imageUrl: "/images/angel.jpg",
    isVerified: true,
  },
  {
    id: 3,
    name: "Thomas Müller",
    role: {
      de: "Hauptpflegender Angehöriger, Luzern",
      en: "Primary Family Caregiver, Lucerne",
      fr: "Proche aidant principal, Lucerne",
      it: "Familiare curante principale, Lucerna",
    },
    canton: "Luzern (LU)",
    quote: {
      de: "Die Organisation der Pflege für meinen Vater schien zunächst überwältigend. Der strukturierte Schritt-für-Schritt-Leitfaden gab der ganzen Familie Sicherheit und einen klaren Weg für die Zusammenarbeit mit den Ärzten.",
      en: "Organizing care for my father initially felt overwhelming. The structured step-by-step roadmap gave our entire family peace of mind and a clear path forward when coordinating with doctors and caregivers.",
      fr: "Organiser les soins de mon père semblait accablant au début. Le guide étape par étape a apporté à toute notre famille une grande sérénité et une voie claire pour collaborer avec les médecins.",
      it: "Organizzare l'assistenza per mio padre sembrava inizialmente insormontabile. La guida passo dopo passo ha dato a tutta la nostra famiglia sicurezza e una direzione chiara per collaborare con i medici.",
    },
    image: "/images/journey_videocall.jpg",
    imageUrl: "/images/journey_videocall.jpg",
    isVerified: true,
  },
];

export const initialFaqs: FaqItem[] = [
  {
    id: "FAQ-01",
    question: {
      de: "Was ist Polaris Care (Pflege Orientierung)?",
      en: "What is Polaris Care (Pflege Orientierung)?",
      fr: "Qu'est-ce que Polaris Care (Pflege Orientierung) ?",
      it: "Che cos'è Polaris Care (Pflege Orientierung)?",
    },
    answer: {
      de: "Pflege Orientierung ist eine unabhängige Schweizer Orientierungsplattform, die pflegende Angehörige mit strukturierter Situationsanalyse, Pflegegrad-Einschätzung und kantonalen Leitfäden unterstützt.",
      en: "Pflege Orientierung is an independent Swiss guidance platform supporting family caregivers with structured situation assessment, care degree estimations, and cantonal resource roadmaps.",
      fr: "Pflege Orientierung est une plateforme suisse indépendante qui aide les proches aidants avec des analyses de situation structurées, des évaluations du niveau de soins et des guides cantonaux.",
      it: "Pflege Orientierung è una piattaforma svizzera indipendente che supporta i familiari curanti con analisi strutturate della situazione, stima del grado di cura e guide cantonali.",
    },
    category: "General",
  },
  {
    id: "FAQ-02",
    question: {
      de: "Wie funktioniert die 12-Fragen Pflege-Kompass Analyse?",
      en: "How does the 12-Question Care Compass Assessment work?",
      fr: "Comment fonctionne l'évaluation en 12 questions du Care Compass ?",
      it: "Come funziona l'analisi in 12 domande del Care Compass?",
    },
    answer: {
      de: "In 12 verständlichen Fragen erfassen wir Wohnsituation, Hilfebedarf, emotionale Belastung und rechtliche Vorsorge, um einen massgeschneiderten Handlungsplan für Ihre Familie zu erstellen.",
      en: "In 12 clear questions, we assess living situation, assistance needs, emotional strain, and legal advance care to create a tailored action roadmap for your family.",
      fr: "En 12 questions claires, nous évaluons la situation de vie, les besoins d'aide, la charge émotionnelle et la prévoyance pour créer un plan d'action sur mesure pour votre famille.",
      it: "In 12 domande chiare, valutiamo la situazione abitativa, i bisogni di assistenza, il carico emotivo e le disposizioni legali per creare un piano d'azione su misura.",
    },
    category: "Assessment",
  },
  {
    id: "FAQ-03",
    question: {
      de: "Sind meine persönlichen und gesundheitlichen Daten geschützt?",
      en: "Are my personal and healthcare data protected under Swiss Law?",
      fr: "Mes données personnelles et de santé sont-elles protégées selon la loi suisse ?",
      it: "I miei dati personali e sanitari sono protetti dalla legge svizzera?",
    },
    answer: {
      de: "Ja. Alle Angaben werden streng nach dem Schweizer Bundesgesetz über den Datenschutz (DSG) sowie den europäischen DSGVO-Standards vertraulich und verschlüsselt verarbeitet.",
      en: "Yes. All data is processed strictly in accordance with the Swiss Federal Data Protection Act (FADP/DSG) and European GDPR standards, fully encrypted and confidential.",
      fr: "Oui. Toutes les données sont traitées de manière strictement confidentielle et chiffrée, conformément à la loi fédérale suisse sur la protection des données (LPD) et au RGPD.",
      it: "Sì. Tutti i dati sono trattati in modo strettamente confidenziale e crittografato, in conformità con la Legge federale svizzera sulla protezione dei dati (LPD) e il GDPR.",
    },
    category: "Privacy & Legal",
  },
  {
    id: "FAQ-04",
    question: {
      de: "Wer finanziert Spitex- und Pflegeleistungen in der Schweiz?",
      en: "Who finances Spitex and home care services in Switzerland?",
      fr: "Qui finance les prestations de soins Spitex en Suisse ?",
      it: "Chi finanzia le prestazioni di cura Spitex in Svizzera?",
    },
    answer: {
      de: "Die ärztlich verordnete Grundpflege wird von der obligatorischen Krankenpflegeversicherung (KVG) gedeckt. Für Betreuungskosten und Selbstbehalte bestehen kantonale Ergänzungsleistungen (EL) sowie Hilflosenentschädigungen der AHV/IV.",
      en: "Doctor-prescribed basic home nursing is covered by compulsory Swiss health insurance (KVG/LAMal). For non-medical caregiving costs, supplementary benefits (EL/PC) and cantonal helplessness allowances (AHV/IV) are available.",
      fr: "Les soins de base prescrits par un médecin sont couverts par l'assurance-maladie obligatoire (LAMal). Pour les coûts d'accompagnement, des prestations complémentaires (PC) et des allocations pour impotent sont disponibles.",
      it: "Le cure di base prescritte dal medico sono coperte dall'assicurazione malattia obbligatoria (LAMal). Per i costi assistenziali sono previste prestazioni complementari (PC) e assegni per grandi invalidi AVS/AI.",
    },
    category: "Finanzen & Spitex",
  },
];


