import {
  AssessmentQuestion,
  AssessmentSubmission,
  ConsultationLead,
  SituationSummary,
  GuidanceResource,
  TestimonialItem,
  FaqItem,
} from "@/types";

export const initialQuestions: AssessmentQuestion[] = [
  {
    id: 1,
    question: "Who are you caring for?",
    subtitle: "Choose the closest match",
    category: "relation",
    options: [
      "A parent or parent-in-law",
      "A partner or spouse",
      "A child",
      "Another family member or close friend",
    ],
    isActive: true,
  },
  {
    id: 2,
    question: "What is their current living arrangement?",
    subtitle: "Select the primary living situation",
    category: "living",
    options: [
      "Living independently at home",
      "Living with me in my household",
      "Living in an assisted care or nursing facility",
      "Other living arrangement",
    ],
    isActive: true,
  },
  {
    id: 3,
    question: "What level of daily assistance is currently needed?",
    subtitle: "Select the most accurate level of daily support",
    category: "assistance",
    options: [
      "Light support (shopping, transport, paperwork)",
      "Moderate daily help (meals, medication, mobility)",
      "Intensive 24/7 care (hygiene, continuous supervision)",
      "Uncertain / currently evaluating needs",
    ],
    isActive: true,
  },
  {
    id: 4,
    question: "Has a formal Pflegegrad (care degree) been assigned?",
    subtitle: "Swiss / German care classification level",
    category: "pflegegrad",
    options: [
      "Yes (Pflegegrad 1 - 2)",
      "Yes (Pflegegrad 3 - 5)",
      "Application is currently in progress",
      "No / Not yet applied",
    ],
    isActive: true,
  },
  {
    id: 5,
    question: "What is your biggest current caregiving challenge?",
    subtitle: "Where do you feel the most pressure today?",
    category: "challenges",
    options: [
      "Navigating medical, legal & insurance bureaucracy",
      "Emotional exhaustion & caregiver burnout",
      "Balancing my job/family with care duties",
      "Financial costs & funding available services",
    ],
    isActive: true,
  },
  {
    id: 6,
    question: "Do you have support from other family members or siblings?",
    subtitle: "Care network and shared responsibilities",
    category: "network",
    options: [
      "Yes, responsibilities are shared well",
      "Some help, but I carry most of the responsibility",
      "No, I am managing everything entirely alone",
      "There is family conflict regarding care decisions",
    ],
    isActive: true,
  },
  {
    id: 7,
    question: "Are professional outpatient care services (Spitex) involved?",
    subtitle: "External nursing and in-home care support",
    category: "spitex",
    options: [
      "Yes, on a daily basis",
      "Yes, a few times per week",
      "We are considering hiring professional support",
      "No professional services at this time",
    ],
    isActive: true,
  },
  {
    id: 8,
    question: "Are essential legal documents in place?",
    subtitle: "Powers of attorney and healthcare directives",
    category: "legal",
    options: [
      "Yes, health proxy and power of attorney are complete",
      "Partially completed / in progress",
      "Not yet created",
      "Unsure what documents are legally required",
    ],
    isActive: true,
  },
  {
    id: 9,
    question: "How is your personal emotional well-being?",
    subtitle: "Your own health and stress levels as a caregiver",
    category: "wellbeing",
    options: [
      "Managing well with good balance",
      "Frequently stressed but coping",
      "Overwhelmed and nearing exhaustion",
      "In urgent need of relief and respite support",
    ],
    isActive: true,
  },
  {
    id: 10,
    question: "What is your Canton or geographic region in Switzerland?",
    subtitle: "Guidance is tailored to local Cantonal regulations",
    category: "canton",
    options: [
      "Zurich / North-Eastern Switzerland",
      "Bern / Mittelland region",
      "Romandie (Geneva, Vaud, Valais, Neuchâtel)",
      "Other Canton / Central Switzerland / Ticino",
    ],
    isActive: true,
  },
  {
    id: 11,
    question: "Are you interested in respite care (Entlastungsangebote)?",
    subtitle: "Temporary day care, holiday relief, or night care",
    category: "respite",
    options: [
      "Yes, urgently looking for temporary relief options",
      "Yes, planning for future respite needs",
      "Would like to learn what respite options exist",
      "Not needed at this time",
    ],
    isActive: true,
  },
  {
    id: 12,
    question: "What is your primary goal from this Care Compass?",
    subtitle: "How Polaris can best guide your next steps",
    category: "goals",
    options: [
      "A structured step-by-step roadmap for our family",
      "Financial assistance and insurance entitlement clarity",
      "Emergency backup and respite planning",
      "Connecting with verified local care partners",
    ],
    isActive: true,
  },
];

export const initialSubmissions: AssessmentSubmission[] = [
  {
    id: "CC-9014",
    caregiver: "Elena Fischer",
    relation: "A parent or parent-in-law",
    living: "Living independently at home",
    careDegree: "Pflegegrad 3 - 5",
    urgency: "High",
    canton: "Zurich (ZH)",
    submittedAt: "10 mins ago",
    score: 84,
    status: "Pending Action",
    answers: {
      1: "A parent or parent-in-law",
      2: "Living independently at home",
      3: "Moderate daily help (meals, medication, mobility)",
      4: "Yes (Pflegegrad 3 - 5)",
      5: "Emotional exhaustion & caregiver burnout",
      6: "No, I am managing everything entirely alone",
      7: "We are considering hiring professional support",
      8: "Partially completed / in progress",
      9: "In urgent need of relief and respite support",
      10: "Zurich / North-Eastern Switzerland",
      11: "Yes, urgently looking for temporary relief options",
      12: "Emergency backup and respite planning",
    },
    advisorNotes: "Caregiver is sole provider with high fatigue. Immediate Spitex respite contact recommended.",
  },
  {
    id: "CC-9013",
    caregiver: "Marc Baumgartner",
    relation: "A partner or spouse",
    living: "Living with me in my household",
    careDegree: "Application is in progress",
    urgency: "Medium",
    canton: "Bern (BE)",
    submittedAt: "35 mins ago",
    score: 62,
    status: "Reviewed",
    answers: {
      1: "A partner or spouse",
      2: "Living with me in my household",
      3: "Moderate daily help (meals, medication, mobility)",
      4: "Application is currently in progress",
      5: "Navigating medical, legal & insurance bureaucracy",
      6: "Some help, but I carry most of the responsibility",
      7: "Yes, a few times per week",
      8: "Yes, health proxy and power of attorney are complete",
      9: "Frequently stressed but coping",
      10: "Bern / Mittelland region",
      11: "Yes, planning for future respite needs",
      12: "Financial assistance and insurance entitlement clarity",
    },
    advisorNotes: "Needs support navigating Bern Cantonal Ergänzungsleistungen (supplementary benefits).",
  },
  {
    id: "CC-9012",
    caregiver: "Sophie Dubois",
    relation: "A parent or parent-in-law",
    living: "Living in an assisted care or nursing facility",
    careDegree: "Pflegegrad 1 - 2",
    urgency: "Normal",
    canton: "Vaud (VD)",
    submittedAt: "2 hours ago",
    score: 38,
    status: "Reviewed",
    answers: {
      1: "A parent or parent-in-law",
      2: "Living in an assisted care or nursing facility",
      3: "Light support (shopping, transport, paperwork)",
      4: "Yes (Pflegegrad 1 - 2)",
      5: "Balancing my job/family with care duties",
      6: "Yes, responsibilities are shared well",
      7: "Yes, on a daily basis",
      8: "Yes, health proxy and power of attorney are complete",
      9: "Managing well with good balance",
      10: "Romandie (Geneva, Vaud, Valais, Neuchâtel)",
      11: "Not needed at this time",
      12: "A structured step-by-step roadmap for our family",
    },
  },
  {
    id: "CC-9011",
    caregiver: "Marco Bernasconi",
    relation: "A child",
    living: "Living with me in my household",
    careDegree: "Pflegegrad 3 - 5",
    urgency: "High",
    canton: "Ticino (TI)",
    submittedAt: "4 hours ago",
    score: 91,
    status: "Pending Action",
    answers: {
      1: "A child",
      2: "Living with me in my household",
      3: "Intensive 24/7 care (hygiene, continuous supervision)",
      4: "Yes (Pflegegrad 3 - 5)",
      5: "Emotional exhaustion & caregiver burnout",
      6: "No, I am managing everything entirely alone",
      7: "Yes, on a daily basis",
      8: "Partially completed / in progress",
      9: "Overwhelmed and nearing exhaustion",
      10: "Other Canton / Central Switzerland / Ticino",
      11: "Yes, urgently looking for temporary relief options",
      12: "Emergency backup and respite planning",
    },
  },
  {
    id: "CC-9010",
    caregiver: "Lukas Keller",
    relation: "Another family member or close friend",
    living: "Living independently at home",
    careDegree: "No / Not yet applied",
    urgency: "Medium",
    canton: "Basel-Stadt (BS)",
    submittedAt: "6 hours ago",
    score: 55,
    status: "Reviewed",
    answers: {
      1: "Another family member or close friend",
      2: "Living independently at home",
      3: "Light support (shopping, transport, paperwork)",
      4: "No / Not yet applied",
      5: "Financial costs & funding available services",
      6: "Some help, but I carry most of the responsibility",
      7: "No professional services at this time",
      8: "Not yet created",
      9: "Frequently stressed but coping",
      10: "Zurich / North-Eastern Switzerland",
      11: "Would like to learn what respite options exist",
      12: "Connecting with verified local care partners",
    },
  },
];

export const initialLeads: ConsultationLead[] = [
  {
    id: "LEAD-301",
    name: "Elena Fischer",
    phone: "+41 44 289 12 04",
    email: "elena.fischer@bluewin.ch",
    canton: "Zurich (ZH)",
    urgency: "High",
    status: "new",
    preferredTime: "Morning (09:00 - 11:00)",
    message: "I am caring for my 84-year-old mother who is nearing Pflegegrad 4. I am feeling completely burnt out and urgently need respite support.",
    assessmentId: "CC-9014",
    createdAt: "Today, 09:15",
    notes: ["Initial inquiry received from Care Compass guidance completion."],
  },
  {
    id: "LEAD-302",
    name: "Dr. Andreas Weber",
    phone: "+41 31 310 44 20",
    email: "andreas.weber@sunrise.ch",
    canton: "Bern (BE)",
    urgency: "Medium",
    status: "contacted",
    preferredTime: "Afternoon (14:00 - 16:00)",
    message: "Looking for independent advice regarding Spitex subsidy reimbursement in Bern.",
    assessmentId: "CC-9013",
    assignedAdvisor: "Dr. Meier (Advisor Zurich)",
    createdAt: "Yesterday, 14:30",
    notes: ["Sent initial introduction email with Bern Spitex documentation.", "Scheduled follow-up phone call for Thursday."],
  },
  {
    id: "LEAD-303",
    name: "Isabelle Favre",
    phone: "+41 22 730 88 11",
    email: "isabelle.favre@gmail.com",
    canton: "Geneva (GE)",
    urgency: "High",
    status: "scheduled",
    preferredTime: "Evening (17:00 - 19:00)",
    message: "Urgent legal directive question regarding health proxy and cantonal guardianship authority (KESB).",
    assessmentId: "CC-9011",
    assignedAdvisor: "Claire Blanc (Romandie Specialist)",
    createdAt: "Aug 20, 11:00",
    notes: ["Phone consultation booked for Aug 24 at 17:30 via Video Call."],
  },
  {
    id: "LEAD-304",
    name: "Hansruedi Steiner",
    phone: "+41 41 220 55 90",
    email: "h.steiner@quickline.ch",
    canton: "Lucerne (LU)",
    urgency: "Standard",
    status: "resolved",
    preferredTime: "Anytime",
    message: "Completed Care Compass for my father. Thank you for the roadmap!",
    assignedAdvisor: "Dr. Meier (Advisor Zurich)",
    createdAt: "Aug 18, 16:20",
    notes: ["Consultation completed. Roadmap sent and accepted."],
  },
];

export const initialSummaries: SituationSummary[] = [
  {
    id: "SUM-01",
    title: "Balanced but Transitioning",
    description: "Your recent assessment indicates a balanced but transitioning care environment. While primary medical needs are being met, there is an increasing demand for emotional support and specialized mobility equipment. We've identified opportunities to reduce caregiver fatigue by 15% through optimized scheduling and the integration of local community resources.",
    targetCategory: "Moderate care, in-home living",
    isActive: true,
  },
  {
    id: "SUM-02",
    title: "High Urgency & Caregiver Respite Needed",
    description: "Your answers indicate acute caregiver fatigue and intensive daily supervision demands. Priority should be given to activating emergency respite options (Entlastungsdienst) and establishing professional outpatient Spitex support to prevent burnout.",
    targetCategory: "High urgency, 24/7 care",
    isActive: true,
  },
  {
    id: "SUM-03",
    title: "Early Stage Orientation & Planning",
    description: "Your caregiving journey is in the early discovery phase. Focus on setting up necessary legal directives (Vorsorgeauftrag, Patiententestament) and establishing contact with local Cantonal advisory centers before acute medical demands arise.",
    targetCategory: "Light support, early stage",
    isActive: true,
  },
];

export const initialResources: GuidanceResource[] = [
  {
    id: "RES-01",
    title: "Physical Therapy Review",
    description: "Review local specialized mobility therapists. Early intervention can significantly improve daily comfort and independence.",
    category: "therapy",
    cantons: ["Zurich (ZH)", "Bern (BE)", "Vaud (VD)", "All Switzerland"],
    linkUrl: "https://polaris-care.ch/resources/therapy",
    isActive: true,
  },
  {
    id: "RES-02",
    title: "Join CareCircle",
    description: "Connect with three other families in your area who are navigating similar care pathways for shared insights and support.",
    category: "community",
    cantons: ["Zurich (ZH)", "Bern (BE)", "Lucerne (LU)", "All Switzerland"],
    linkUrl: "https://polaris-care.ch/resources/carecircle",
    isActive: true,
  },
  {
    id: "RES-03",
    title: "Equipment & Home Modification Guide",
    description: "Explore our curated guide on home modifications and adaptive tools specifically for late-stage mobility support.",
    category: "equipment",
    cantons: ["All Switzerland"],
    linkUrl: "https://polaris-care.ch/resources/equipment",
    isActive: true,
  },
];

export const initialTestimonials: TestimonialItem[] = [
  {
    id: 1,
    name: "Sarah Renner",
    role: "Family Caregiver, Zurich",
    quote: "The Care Compass was simple to complete, yet the recommendations felt thoughtful and relevant. Instead of endless searching online, I finally had clear guidance tailored to my situation.",
    image: "/images/sarah.jpg",
    canton: "Zurich (ZH)",
    isVerified: true,
  },
  {
    id: 2,
    name: "Angel Dia",
    role: "Spouse Caregiver, Bern",
    quote: "Pflege Orientierung helped us clarify our insurance entitlements and find the right local Spitex service within days. The relief our family felt was truly immeasurable.",
    image: "/images/angel.jpg",
    canton: "Bern (BE)",
    isVerified: true,
  },
  {
    id: 3,
    name: "Thomas Mueller",
    role: "Primary Caregiver, Lucerne",
    quote: "Navigating elder care for my father felt completely overwhelming before this. The step-by-step roadmap gave our whole family a calm, structured plan to move forward.",
    image: "/images/journey_videocall.jpg",
    canton: "Lucerne (LU)",
    isVerified: true,
  },
];

export const initialFaqs: FaqItem[] = [
  {
    id: "FAQ-01",
    question: "What is Polaris Care (Pflege Orientierung)?",
    answer: "Pflege Orientierung is an independent Swiss guidance platform designed to assist family caregivers with structured navigation, assessments, and actionable care pathways tailored to their individual situation.",
    category: "General",
  },
  {
    id: "FAQ-02",
    question: "How does the Care Compass assessment work?",
    answer: "The Care Compass is a gentle 12-question assessment that evaluates your living arrangement, care degree (Pflegegrad), emotional well-being, and legal preparation to generate personalized recommendations.",
    category: "Assessment",
  },
  {
    id: "FAQ-03",
    question: "Is my personal and medical data protected?",
    answer: "Yes. All assessment data is strictly stored on your device in compliance with the Swiss Federal Act on Data Protection (FADP) and European GDPR standards.",
    category: "Privacy & Legal",
  },
];
